# Generated by Django 4.2.30 on 2026-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título de la propiedad')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
            ],
        ),
    ]
