# Generated by Django 4.2.30 on 2026-06-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('rol', models.CharField(choices=[('cliente', 'CLIENTE'), ('admin', 'ADMIN')], default='cliente', max_length=20)),
            ],
        ),
    ]
