# Generated by Django 4.2.30 on 2026-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Telefonico')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
            ],
        ),
    ]
