# Generated by Django 4.2.30 on 2026-06-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensajeContacto',
            new_name='Contacto',
        ),
    ]
